const listColorComponents = {
    // HNavbars list
    
    "navbar1text":"#7d7d7d",
    "navbar1bg":"transparent",
    "navbar1btn":"transparent",
    "navbar1Updatetext":"",
    "navbar1Updatebg":"",
    "navbar1Updatebtn":"",
    // 141C24
    "navbar2text":"#141C24",
    "navbar2bg":"transparent",
    "navbar2btn":"red",
    "navbar2Updatetext":"green",
    "navbar2Updatebg":"",
    "navbar2Updatebtn":"",
    
    "navbar3text":"",
    "navbar3bg":"",
    "navbar3btn":"",
    "navbar3Updatetext":"",
    "navbar3Updatebg":"",
    "navbar3Updatebtn":"",
    
    "navbar4text":"",
    "navbar4bg":"",
    "navbar4btn":"",
    "navbar4Updatetext":"",
    "navbar4Updatebg":"",
    "navbar4Updatebtn":"",
    
    "navbar5text":"",
    "navbar5bg":"",
    "navbar5btn":"",
    "navbar5Updatetext":"",
    "navbar5Updatebg":"",
    "navbar5Updatebtn":"",
    
    
    // Heroes list
    "hero1text":"",
    "hero1bg":"",
    "hero1btn":"",
    "hero1Updatetext":"",
    "hero1Updatebg":"",
    "hero1Updatebtn":"",
    
    "hero2text":"",
    "hero2bg":"",
    "hero2btn":"",
    "hero2Updatetext":"",
    "hero2Updatebg":"",
    "hero2Updatebtn":"",
    
    "hero3text":"",
    "hero3bg":"",
    "hero3btn":"",
    "hero3Updatetext":"",
    "hero3Updatebg":"",
    "hero3Updatebtn":"",
    
    "hero4text":"",
    "hero4bg":"",
    "hero4btn":"",
    "hero4Updatetext":"",
    "hero4Updatebg":"",
    "hero4Updatebtn":"",
    
    "hero5text":"",
    "hero5bg":"",
    "hero5btn":"",
    "hero5Updatetext":"",
    "hero5Updatebg":"",
    "hero5Updatebtn":"",
    
    "hero6text":"",
    "hero6bg":"",
    "hero6btn":"",
    "hero6Updatetext":"",
    "hero6Updatebg":"",
    "hero6Updatebtn":"",
    
    "hero7text":"",
    "hero7bg":"",
    "hero7btn":"",
    "hero7Updatetext":"",
    "hero7Updatebg":"",
    "hero7Updatebtn":"",
    
    "hero8text":"",
    "hero8bg":"",
    "hero8btn":"",
    "hero8Updatetext":"",
    "hero8Updatebg":"",
    "hero8Updatebtn":"",
    
    "hero9text":"",
    "hero9bg":"",
    "hero9btn":"",
    "hero9Updatetext":"",
    "hero9Updatebg":"",
    "hero9Updatebtn":"",
    
    "hero10text":"",
    "hero10bg":"",
    "hero10btn":"",
    "hero10Updatetext":"",
    "hero10Updatebg":"",
    "hero10Updatebtn":"",
    
    "hero11text":"",
    "hero11bg":"",
    "hero11btn":"",
    "hero11Updatetext":"",
    "hero11Updatebg":"",
    "hero11Updatebtn":"",
    
    "hero12text":"",
    "hero12bg":"",
    "hero12btn":"",
    "hero12Updatetext":"",
    "hero12Updatebg":"",
    "hero12Updatebtn":"",
    
    "hero13text":"",
    "hero13bg":"",
    "hero13btn":"",
    "hero13Updatetext":"",
    "hero13Updatebg":"",
    "hero13Updatebtn":"",
    
    "hero14text":"",
    "hero14bg":"",
    "hero14btn":"",
    "hero14Updatetext":"",
    "hero14Updatebg":"",
    "hero14Updatebtn":"",
    

    // Contents list
    "content1text":"",
    "content1bg":"",
    "content1btn":"",
    "content1Updatetext":"",
    "content1Updatebg":"",
    "content1Updatebtn":"",
    
    "content2text":"",
    "content2bg":"",
    "content2btn":"",
    "content2Updatetext":"",
    "content2Updatebg":"",
    "content2Updatebtn":"",
    
    "content3text":"",
    "content3bg":"",
    "content3btn":"",
    "content3Updatetext":"",
    "content3Updatebg":"",
    "content3Updatebtn":"",
    
    "content4text":"",
    "content4bg":"",
    "content4btn":"",
    "content4Updatetext":"",
    "content4Updatebg":"",
    "content4Updatebtn":"",
    
    "content5text":"",
    "content5bg":"",
    "content5btn":"",
    "content5Updatetext":"",
    "content5Updatebg":"",
    "content5Updatebtn":"",
    
    "content6text":"",
    "content6bg":"",
    "content6btn":"",
    "content6Updatetext":"",
    "content6Updatebg":"",
    "content6Updatebtn":"",
    
    "content7text":"",
    "content7bg":"",
    "content7btn":"",
    "content7Updatetext":"",
    "content7Updatebg":"",
    "content7Updatebtn":"",
    
    "content8text":"",
    "content8bg":"",
    "content8btn":"",
    "content9Updatetext":"",
    "content9Updatebg":"",
    "content9Updatebtn":"",
    
    "content9text":"",
    "content9bg":"",
    "content9btn":"",
    "content9Updatetext":"",
    "content9Updatebg":"",
    "content9Updatebtn":"",
    
    "content10text":"",
    "content10bg":"",
    "content10btn":"",
    "content10Updatetext":"",
    "content10Updatebg":"",
    "content10Updatebtn":"",
    
    "content11text":"",
    "content11bg":"",
    "content11btn":"",
    "content11Updatetext":"",
    "content11Updatebg":"",
    "content11Updatebtn":"",
    
    "content12text":"",
    "content12bg":"",
    "content12btn":"",
    "content12Updatetext":"",
    "content12Updatebg":"",
    "content12Updatebtn":"",
    
    "content13text":"",
    "content13bg":"",
    "content13btn":"",
    "content13Updatetext":"",
    "content13Updatebg":"",
    "content13Updatebtn":"",
    
    "content14text":"",
    "content14bg":"",
    "content14btn":"",
    "content14Updatetext":"",
    "content14Updatebg":"",
    "content14Updatebtn":"",
    
    "content15text":"",
    "content15bg":"",
    "content15btn":"",
    "content15Updatetext":"",
    "content15Updatebg":"",
    "content15Updatebtn":"",
    
    "content16text":"",
    "content16bg":"",
    "content16btn":"",
    "content16Updatetext":"",
    "content16Updatebg":"",
    "content16Updatebtn":"",
    
    "content17text":"",
    "content17bg":"",
    "content17btn":"",
    "content17Updatetext":"",
    "content17Updatebg":"",
    "content17Updatebtn":"",
    
    "content18text":"",
    "content18bg":"",
    "content18btn":"",
    "content18Updatetext":"",
    "content18Updatebg":"",
    "content18Updatebtn":"",
    
    "content19text":"",
    "content19bg":"",
    "content19btn":"",
    "content19Updatetext":"",
    "content19Updatebg":"",
    "content19Updatebtn":"",
    
    "content20text":"",
    "content20bg":"",
    "content20btn":"",
    "content20Updatetext":"",
    "content20Updatebg":"",
    "content20Updatebtn":"",
    
    "content21text":"",
    "content21bg":"",
    "content21btn":"",
    "content21Updatetext":"",
    "content21Updatebg":"",
    "content21Updatebtn":"",
    
    "content22text":"",
    "content22bg":"",
    "content22btn":"",
    "content22Updatetext":"",
    "content22Updatebg":"",
    "content22Updatebtn":"",
    
    "content23text":"",
    "content23bg":"",
    "content23btn":"",
    "content23Updatetext":"",
    "content23Updatebg":"",
    "content23Updatebtn":"",
    
    "content24text":"",
    "content24bg":"",
    "content24btn":"",
    "content24Updatetext":"",
    "content24Updatebg":"",
    "content24Updatebtn":"",
    
    "content25text":"",
    "content25bg":"",
    "content25btn":"",
    "content25Updatetext":"",
    "content25Updatebg":"",
    "content25Updatebtn":"",
    
    "content26text":"",
    "content26bg":"",
    "content26btn":"",
    "content26Updatetext":"",
    "content26Updatebg":"",
    "content26Updatebtn":"",


    // Footers list
    "footer1text":"",
    "footer1bg":"",
    "footer1btn":"",
    "footer1Updatetext":"",
    "footer1Updatebg":"",
    "footer1Updatebtn":"",
    
    "footer2text":"",
    "footer2bg":"",
    "footer2btn":"",
    "footer2Updatetext":"",
    "footer2Updatebg":"",
    "footer2Updatebtn":"",
    
    "footer3text":"",
    "footer3bg":"",
    "footer3btn":"",
    "footer3Updatetext":"",
    "footer3Updatebg":"",
    "footer3Updatebtn":"",
    
    "footer4text":"",
    "footer4bg":"",
    "footer4btn":"",
    "footer4Updatetext":"",
    "footer4Updatebg":"",
    "footer4Updatebtn":"",
    
    "footer5text":"",
    "footer5bg":"",
    "footer5btn":"",
    "footer5Updattexte":"",
    "footer5Updatbge":"",
    "footer5Updatbtne":""
    
}

export default listColorComponents